version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mytransactiondb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mytransactiondb
      DATABASE_SSL: "false"
      SAFARICOM_CONSUMER_KEY: ${SAFARICOM_CONSUMER_KEY}
      SAFARICOM_CONSUMER_SECRET: ${SAFARICOM_CONSUMER_SECRET}
      SAFARICOM_OAUTH_URL: ${SAFARICOM_OAUTH_URL}
      SAFARICOM_STK_PUSH_URL: ${SAFARICOM_STK_PUSH_URL}
      SAFARICOM_BUY_GOODS_URL: ${SAFARICOM_BUY_GOODS_URL}
      SAFARICOM_TILL_PAYMENT_URL: ${SAFARICOM_TILL_PAYMENT_URL}
      SAFARICOM_PAYBILL_URL: ${SAFARICOM_PAYBILL_URL}
      SAFARICOM_B2C_URL: ${SAFARICOM_B2C_URL}
      SAFARICOM_SHORT_CODE: ${SAFARICOM_SHORT_CODE}
      SAFARICOM_PASSWORD: ${SAFARICOM_PASSWORD}
      SAFARICOM_TILL_NUMBER: ${SAFARICOM_TILL_NUMBER}
      SAFARICOM_SECURITY_CREDENTIAL: ${SAFARICOM_SECURITY_CREDENTIAL}
      SAFARICOM_INITIATOR_NAME: ${SAFARICOM_INITIATOR_NAME}
      CALLBACK_URL: ${CALLBACK_URL}
      APIBARA_ENDPOINT: ${APIBARA_ENDPOINT}
      APIBARA_TOKEN: ${APIBARA_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "yarn sequelize db:migrate && yarn start"

volumes:
  pgdata:
